import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import {
  TitleDescription,
  SearchVod,
 
  HeaderMain,
} from "@/elements";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <HeaderMain toggleSearch={true} />
        <TitleDescription />

        <SearchVod />
      </main>
    </>
  );
};

export default Home;
