import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import {
  TitleDescription,
  SearchVod,
  VodThumbnails,
  HeaderMain,
} from "@/elements";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-h-screen min-h-screen">
        <HeaderMain toggleSearch={false} />
        <div className="">
          <TitleDescription />
          <div className="mt-12 flex">
            <VodThumbnails />
          </div>
          <p className="text-md mt-10 px-5 text-center font-medium text-white md:text-lg lg:text-2xl">
            Paste in a <span className="text-purple-400">Twitch VOD</span> and
            find the most{" "}
            <span className="font-bold uppercase text-red-500">
              hype moments!!!
            </span>
          </p>
          <SearchVod />
        </div>
      </main>
    </>
  );
};

export default Home;
